name: AutoPrompt

channels:
  - conda-forge

dependencies:
  - python~=3.10
  - pip>=2.22.0
  - openai
  - langchain
  - pandas
  - wandb
  - transformers
  - tqdm
  - faiss-cpu
  - sentence-transformers
  - pip:
      - prodict
      - argilla
      - schedule
      - pandas
      - easydict
