annotator:
    method : 'argilla'
    config:
        api_url: 'https://us3r-070-argilla.hf.space'
        api_key: 'admin.apikey'
        workspace: 'admin'
        time_interval: 5

dataset:
    records_path: 'dataset/generation_dataset.csv'
    initial_dataset: 'dataset/generation_dataset.csv'
    # label_schema: ["1","2","3","4","5"]
    max_samples: 20
    semantic_sampling: False

predictor:
    method : 'llm'
    config:
        prompt: 'prompts/predictor_completion/prediction_generation.prompt'
        mini_batch_size: 1
        llm:
            type: 'OpenAI'
            name: 'gpt-4o-mini' #'gpt-3.5-turbo-1106'
            temperature: 0.7
        num_workers: 7

meta_prompts:
    folder: 'prompts/meta_prompts_generation'
    warmup: 1

eval:
    function_name: 'ranking'
    error_threshold: 4

