
dataset:
    records_path: 'dataset/generation_dataset.csv'
    initial_dataset: 'dataset/generation_dataset.csv'
    label_schema: ["1","2","3","4","5"]
    max_samples: 40
    semantic_sampling: False # Change to True in case you don't have M1. Currently there is an issue with faiss and M1

meta_prompts:
    folder: 'prompts/meta_prompts_ranking'