use_wandb: False
dataset:
    name: 'dataset'
    records_path: null
    num_initialize_samples: 8
    initial_dataset: 'dump/gen_dataset1.csv'
    label_schema: ["1","2","3","4","5"]
    max_samples: 65

estimator:
    method : ''

predictor:
    method : 'llm'
    config:
        llm:
            type: 'OpenAI'
            name: 'gpt-3.5-turbo-0613'
#            async_params:
#                retry_interval: 10
#                max_retries: 2
#            model_kwargs: {"seed": 220}
        num_workers: 5
        prompt: 'prompts/predictor_completion/prediction_generation.prompt'
        mini_batch_size: 1
        mode: 'prediction'

meta_prompts:
    folder: 'prompts/meta_prompts_generation'
    num_err_prompt: 1  #number of error examples per sample in the prompt generation
    num_err_samples: 2 #number of error examples per sample in the sample generation
    history_length: 4
    num_generated_samples: 10
    num_initialize_samples: 10
    samples_generation_batch: 10
    num_workers: 5
    warmup: 4

eval:
    function_name: 'ranking'
    num_large_errors: 4
    num_boundary_predictions : 0
    error_threshold: 4
    num_steps: 2

llm:
    type: 'OpenAI'
    name: 'gpt-4-1106-preview'

stop_criteria:
    max_usage: 0.5
    patience: 3
    min_delta: 0.05
