estimator:
    method : ''

predictor:
    method : 'llm'
    config:
        prompt: 'prompts/predictor_completion/prediction_generation.prompt'
        mini_batch_size: 1

meta_prompts:
    folder: 'prompts/meta_prompts_generation'

eval:
    function_name: 'ranking'
    error_threshold: 5
    num_initialize_samples: 50
